=== charrls/XML-Schemas/src/vehiculos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="fabricacion" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="inicio" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" minOccurs="1" maxOccurs="1"/>
                                                    <xs:element name="mes" minOccurs="1" maxOccurs="1"/>
                                                    <xs:element name="año" minOccurs="1" maxOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="fin" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" minOccurs="1" maxOccurs="1"/>
                                                    <xs:element name="mes" minOccurs="1" maxOccurs="1"/>
                                                    <xs:element name="año" minOccurs="1" maxOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="modificaciones" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modificacion" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== charrls/XML-Schemas/src/vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>


<vehiculos xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vehiculos.xsd">
    <vehiculo>
        <nombre>Count Zero</nombre>
        <modelo>Series I, 80"</modelo>
        <fabricacion>
            <inicio>
                <dia>21</dia>
                <mes>July</mes>
                <a単o>1949</a単o>
            </inicio>
            <fin>
                <dia>9</dia>
                <mes>August</mes>
                <a単o>1949</a単o>
            </fin>
        </fabricacion>
        <modificaciones>
        <modificacion>Change Engine</modificacion>
        <modificacion>Change pedals</modificacion>
        <modificacion>Change gearbox</modificacion>
        <modificacion>Fit Rollcage</modificacion>
        </modificaciones>
    </vehiculo>
</vehiculos>
